import Navbar from "@/components/Navbar/Navbar";
import styles from "./page.module.scss";
import Spline from '@splinetool/react-spline';

export default function Home() {
  return (
    <div className={styles.page}>
        <Navbar/>
        <div className={styles.text}>
        <h1>RESUME RECIPIES GENERATED BY AI</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero, suscipit alias facilis quo corrupti tempore reprehenderit ex sapienteipsum animi voluptatibus quidem iste mollitia quaerat repudiandae! Laborum ut soluta repellendus aspernatur?</p>
        </div>
        <div className={styles.bg}>
            <Spline scene="https://prod.spline.design/4jSxKgN74H-9eCOe/scene.splinecode" /> 
        </div>
    </div>
  );
}
